### ISSUE TITLE
Cheating with build?

### ISSUE THREAD

**Issue by mbndr** [m4ll0k/Spaghetti#11]
Hi, I really like your project, but looking into your readme file I saw that your build badge is just a custom badge without running any tests. That's kind of cheating, isn't it? I don't know if many people do this, just realized it coincidentally.

**Comment by m4ll0k** [comment]
I don't understand what you say!!

**Comment by mbndr** [comment]
The build-passing badge is usually genrated by a tool like https://travis-ci.org. Unit tests are executed on their servers and depending on their success or failure the badge shows the build status.

**Comment by m4ll0k** [comment]
ok
