### ISSUE TITLE
No default for scan mode

### ISSUE THREAD

**Issue by mboelen** [m4ll0k/Spaghetti#16]
Providing only a URL but no scan mode, will result in an error:

```
Traceback (most recent call last):
  File "spaghetti.py", line 173, in <module>
    main.main(sys.argv[1:])
  File "spaghetti.py", line 84, in main
    if self.scan == "0":
```

I suggest adding a default value, in case people like me forgot to add it and only provide URL. Otherwise show an error.

BTW, the tool itself looks good and useful. Initial review here: https://linuxsecurity.expert/tools/spaghetti/
(would be great if you can add tags/releases to the project, so we can pick up new releases)

**Comment by m4ll0k** [comment]
`--redirect False`

**Comment by m4ll0k** [comment]
Thanks bro
